add_newline = false
format = """\

$status$directory\
$git_branch\
$git_status\
$git_state\
$git_commit\
 """

[directory]
format = "[ $path ]($style)[](fg:#333333)"
style = "fg:#999999 bg:#333333"
truncation_length = 5
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1
repo_root_format = "[ $before_root_path[$repo_root]($repo_root_style)$path ]($style)"
repo_root_style = "bold fg:#ffffff bg:#333333"
before_repo_root_style = "fg:#999999 bg:#333333"

[git_branch]
format = "[](fg:#333333 bg:#addc10)[ $symbol$branch]($style)"
symbol = " "
style = "fg:#0c4801 bg:#addc10"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "fg:#0c4801 bg:#addc10"
stashed = "\\$"
modified = "…"
staged = "+"
untracked = "?"
ahead = "⬆"
behind = "⬇"
diverged = "⬍"

[git_state]
format = "[ $state( $progress_current/$progress_total) ]($style)"
style = "fg:#0c4801 bg:#addc10"

[git_commit]
disabled = false
only_detached = false
format = "[](fg:#addc10)"
tag_disabled = true

[status]
disabled = false
format = "[ ! ](bg:red fg:white bold)"
